 //@version=6
indicator(title="MHT True Range", shorttitle="MHT TR", overlay=false, timeframe="1", timeframe_gaps=true)

string maTypeInput = input.string("EMA", "Moving average type", ["EMA", "SMA"], display = display.none)
int maLenInput = input.int(21, "MA length", 1)
lengthB = input.int(title="Basic range minutes", defval=10, minval=1)
lengthC = input.int(title="Cumulative range minutes", defval=3, minval=1)
lineW = input.int(title="Line width", defval=3, minval=1)
bandTarget = input.float(title="Target range", defval=33, minval=1, step=1)
bandCasio = input.float(title="Casio range", defval=20, minval=1, step=1)
fullRange = math.abs(high - low)

float cumulativeRange = fullRange
for i = 1 to (lengthC -1)
    cumulativeRange := cumulativeRange + fullRange[i]

basicRange = math.abs(ta.highest(high,lengthB) - ta.lowest(low,lengthB))

color sColor = basicRange > bandTarget ? color.rgb(76, 175, 79, 33) : basicRange < bandTarget and basicRange > bandCasio ? color.rgb(255, 153, 0, 33) : color.rgb(255, 82, 82, 33)
color cColor = cumulativeRange > bandTarget ? color.rgb(76, 175, 79, 33) : cumulativeRange < bandTarget and basicRange > bandCasio ? color.rgb(255, 153, 0, 33) : color.rgb(255, 82, 82, 33)

plot(cumulativeRange, title = "Cumulative Range", color=cColor, style = plot.style_columns)
plot(basicRange, title = "Basic Range", color=sColor, style = plot.style_columns)