//@version=6
indicator(title="Average True Range", shorttitle="ATR", overlay=false, timeframe="1", timeframe_gaps=true)
length = input.int(title="Length", defval=21, minval=1)
band = input.float(title="ATR band", defval=10, minval=1, step=0.1)
smoothing = input.string(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
ma_function(source, length) =>
	switch smoothing
		"RMA" => ta.rma(source, length)
		"SMA" => ta.sma(source, length)
		"EMA" => ta.ema(source, length)
		=> ta.wma(source, length)
plot(ma_function(ta.tr(true), length), title = "ATR", color=color.new(#0591ee, 16), style = plot.style_columns)
atrBand = hline(band, "ATR Lower Band", color=#787B86)
zero = hline(0, "Zero line", color=#787B86)
fill(atrBand,zero, color=color.rgb(5, 18, 195, 33), title = "Low Volatility Zone")